[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "siyi_monitoring"
version = "0.1.0"
description = "An integrated teleoperation interface for SIYI controllers featuring robust SBUS data filtering and real-time vision feedback via WebRTC"
readme = "README.md"
requires-python = ">=3.11" # tomllib 사용을 위해 3.11 권장
dependencies = [
    "pyserial",
    "rich",
    "PyGObject",
]

[project.scripts]
sbus-run = "main:main"

[tool.setuptools.packages.find]
where = ["src"]